# mkdocs.yml
theme:
  logo: https://raw.githubusercontent.com/audunsh/btjenesten/master/graphics/b_logo_3.png 
  name: "material"
  palette:
    primary: blue grey

site_name : B-tjenesten

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
